# Generated by Django 5.0.3 on 2024-03-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xizmatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('icon', models.FileField(upload_to='xizmatlar/')),
            ],
        ),
        migrations.CreateModel(
            name='Xodimlarimiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AddField(
            model_name='avtoservis_haqida',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
