# Generated by Django 5.0.3 on 2024-03-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_xizmatlar_xodimlarimiz_delete_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xizmatlar',
            name='icon',
        ),
        migrations.AddField(
            model_name='xizmatlar',
            name='img',
            field=models.ImageField(default=1, upload_to='xizmatlar/'),
            preserve_default=False,
        ),
    ]
