# Generated by Django 5.0.3 on 2024-03-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_xizmatlar_icon_xizmatlar_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='xodimlarimiz',
            name='img',
            field=models.ImageField(default=1, upload_to='xodimlar/'),
            preserve_default=False,
        ),
    ]
